// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveToPool(arg1) {
  return window['go']['waillib']['App']['ArchiveToPool'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['waillib']['App']['DeleteSkill'](arg1);
}

export function DeleteSkillFromPool(arg1) {
  return window['go']['waillib']['App']['DeleteSkillFromPool'](arg1);
}

export function GetAgentSkillsDir(arg1) {
  return window['go']['waillib']['App']['GetAgentSkillsDir'](arg1);
}

export function GetConfig() {
  return window['go']['waillib']['App']['GetConfig']();
}

export function GetStats() {
  return window['go']['waillib']['App']['GetStats']();
}

export function ImportToPool(arg1) {
  return window['go']['waillib']['App']['ImportToPool'](arg1);
}

export function Install(arg1, arg2) {
  return window['go']['waillib']['App']['Install'](arg1, arg2);
}

export function InstallMarketSkill(arg1, arg2) {
  return window['go']['waillib']['App']['InstallMarketSkill'](arg1, arg2);
}

export function InstallToAgent(arg1, arg2, arg3) {
  return window['go']['waillib']['App']['InstallToAgent'](arg1, arg2, arg3);
}

export function InstallToProject(arg1, arg2, arg3) {
  return window['go']['waillib']['App']['InstallToProject'](arg1, arg2, arg3);
}

export function InstallToProjectForAgent(arg1, arg2, arg3, arg4) {
  return window['go']['waillib']['App']['InstallToProjectForAgent'](arg1, arg2, arg3, arg4);
}

export function ListAgents() {
  return window['go']['waillib']['App']['ListAgents']();
}

export function ListPool() {
  return window['go']['waillib']['App']['ListPool']();
}

export function ListSkills() {
  return window['go']['waillib']['App']['ListSkills']();
}

export function OpenDirectory(arg1) {
  return window['go']['waillib']['App']['OpenDirectory'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['waillib']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['waillib']['App']['OpenFileDialog'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['waillib']['App']['OpenURL'](arg1);
}

export function RunDoctor() {
  return window['go']['waillib']['App']['RunDoctor']();
}

export function SaveConfig(arg1) {
  return window['go']['waillib']['App']['SaveConfig'](arg1);
}

export function ScanLocal(arg1) {
  return window['go']['waillib']['App']['ScanLocal'](arg1);
}

export function Search(arg1) {
  return window['go']['waillib']['App']['Search'](arg1);
}

export function SearchMarket(arg1) {
  return window['go']['waillib']['App']['SearchMarket'](arg1);
}

export function Uninstall(arg1, arg2) {
  return window['go']['waillib']['App']['Uninstall'](arg1, arg2);
}
