// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {operations} from '../models';
import {waillib} from '../models';

export function ArchiveToPool(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteSkillFromPool(arg1:string):Promise<void>;

export function GetAgentSkillsDir(arg1:string):Promise<string>;

export function GetConfig():Promise<models.Config>;

export function GetStats():Promise<operations.SkillStats>;

export function ImportToPool(arg1:string):Promise<void>;

export function Install(arg1:string,arg2:waillib.InstallUIOptions):Promise<Array<waillib.InstallUILog>>;

export function InstallToAgent(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function InstallToProject(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function ListAgents():Promise<Array<waillib.AgentInfo>>;

export function ListPool():Promise<Array<waillib.DiscoveredSkill>>;

export function ListSkills():Promise<Array<waillib.ListedSkill>>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function RunDoctor():Promise<operations.HealthReport>;

export function SaveConfig(arg1:models.Config):Promise<void>;

export function ScanLocal(arg1:string):Promise<Array<waillib.DiscoveredSkill>>;

export function Search(arg1:string):Promise<Array<models.ResolvedSkill>>;

export function Uninstall(arg1:string,arg2:string):Promise<void>;
