// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {api} from '../models';

export function BatchClean(arg1:models.BatchCleanCriteria):Promise<models.BatchCleanResult>;

export function BatchSyncSkills(arg1:models.BatchSyncRequest):Promise<models.BatchSyncResult>;

export function CheckHealth():Promise<models.HealthReport>;

export function CleanGlobalLibrary(arg1:boolean):Promise<models.CleanResult>;

export function CleanOrphanedSymlinks(arg1:string):Promise<number>;

export function DeleteSkillVersion(arg1:string,arg2:string):Promise<void>;

export function FixBrokenSymlinks(arg1:string):Promise<number>;

export function GetAgentStats(arg1:string):Promise<models.AgentStats>;

export function GetConfig():Promise<models.Config>;

export function GetMarketConfig():Promise<models.SkillMarketConfig>;

export function GetSkillStats(arg1:string):Promise<models.SkillStats>;

export function GetUsageDashboard():Promise<models.UsageDashboard>;

export function Install(arg1:api.InstallRequest):Promise<Array<api.InstallResult>>;

export function ListAgents():Promise<Record<string, models.Agent>>;

export function ListGlobalSkillsWithAgents():Promise<Array<models.GlobalSkillWithAgents>>;

export function ListMarketSkills(arg1:string):Promise<Array<models.MarketSkill>>;

export function ListSkillVersions(arg1:string):Promise<Array<models.VersionInfo>>;

export function ListSkills():Promise<Array<models.Skill>>;

export function MigrateProjectSkillToLibrary(arg1:string,arg2:string):Promise<models.MigrateResult>;

export function ScanMarket():Promise<models.ScanMarketResult>;

export function ScanProjectSkills(arg1:string):Promise<Array<models.ProjectSkill>>;

export function SetMarketConfig(arg1:models.SkillMarketConfig):Promise<void>;

export function SkillspoolRoot():Promise<string>;

export function SwitchSkillVersion(arg1:string,arg2:string):Promise<void>;

export function UninstallFromProject(arg1:string,arg2:string,arg3:string):Promise<void>;
