// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSkillTag(arg1, arg2) {
  return window['go']['main']['App']['AddSkillTag'](arg1, arg2);
}

export function BatchClean(arg1) {
  return window['go']['main']['App']['BatchClean'](arg1);
}

export function BatchSyncSkills(arg1) {
  return window['go']['main']['App']['BatchSyncSkills'](arg1);
}

export function CheckHealth() {
  return window['go']['main']['App']['CheckHealth']();
}

export function CleanGlobalLibrary(arg1) {
  return window['go']['main']['App']['CleanGlobalLibrary'](arg1);
}

export function CleanOrphanedSymlinks(arg1) {
  return window['go']['main']['App']['CleanOrphanedSymlinks'](arg1);
}

export function DeleteSkillVersion(arg1, arg2) {
  return window['go']['main']['App']['DeleteSkillVersion'](arg1, arg2);
}

export function EnsureRuntime() {
  return window['go']['main']['App']['EnsureRuntime']();
}

export function FixBrokenSymlinks(arg1) {
  return window['go']['main']['App']['FixBrokenSymlinks'](arg1);
}

export function GetAgentStats(arg1) {
  return window['go']['main']['App']['GetAgentStats'](arg1);
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMarketConfig() {
  return window['go']['main']['App']['GetMarketConfig']();
}

export function GetSkillStats(arg1) {
  return window['go']['main']['App']['GetSkillStats'](arg1);
}

export function GetSkillTags(arg1) {
  return window['go']['main']['App']['GetSkillTags'](arg1);
}

export function GetSkillspoolRoot() {
  return window['go']['main']['App']['GetSkillspoolRoot']();
}

export function GetUsageDashboard() {
  return window['go']['main']['App']['GetUsageDashboard']();
}

export function Install(arg1) {
  return window['go']['main']['App']['Install'](arg1);
}

export function InstallFromClawHub(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallFromClawHub'](arg1, arg2, arg3);
}

export function InstallSkillToAgent(arg1, arg2) {
  return window['go']['main']['App']['InstallSkillToAgent'](arg1, arg2);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListGlobalSkillsWithAgents() {
  return window['go']['main']['App']['ListGlobalSkillsWithAgents']();
}

export function ListMarketSkills(arg1) {
  return window['go']['main']['App']['ListMarketSkills'](arg1);
}

export function ListSkillVersions(arg1) {
  return window['go']['main']['App']['ListSkillVersions'](arg1);
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListSkillsWithStatus() {
  return window['go']['main']['App']['ListSkillsWithStatus']();
}

export function MigrateProjectSkillToLibrary(arg1, arg2) {
  return window['go']['main']['App']['MigrateProjectSkillToLibrary'](arg1, arg2);
}

export function RemoveSkillTag(arg1, arg2) {
  return window['go']['main']['App']['RemoveSkillTag'](arg1, arg2);
}

export function RuntimeStatus() {
  return window['go']['main']['App']['RuntimeStatus']();
}

export function ScanMarket() {
  return window['go']['main']['App']['ScanMarket']();
}

export function ScanProjectSkills(arg1) {
  return window['go']['main']['App']['ScanProjectSkills'](arg1);
}

export function SearchClawHub(arg1) {
  return window['go']['main']['App']['SearchClawHub'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SetMarketConfig(arg1) {
  return window['go']['main']['App']['SetMarketConfig'](arg1);
}

export function SetSkillspoolRoot(arg1) {
  return window['go']['main']['App']['SetSkillspoolRoot'](arg1);
}

export function SkillspoolRoot() {
  return window['go']['main']['App']['SkillspoolRoot']();
}

export function SwitchSkillVersion(arg1, arg2) {
  return window['go']['main']['App']['SwitchSkillVersion'](arg1, arg2);
}

export function UninstallFromProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['UninstallFromProject'](arg1, arg2, arg3);
}

export function UninstallSkillFromAgent(arg1, arg2) {
  return window['go']['main']['App']['UninstallSkillFromAgent'](arg1, arg2);
}
